export const ORGANIZATION_TYPES = {
  PRIVATE_BUS_COMPANY: 'PRIVATE_BUS_COMPANY',
  TRANSPORT_ASSOCIATION: 'TRANSPORT_ASSOCIATION',
  COMPANY: 'COMPANY', // supported for legacy compatibility
};

export const ALL_ORGANIZATION_TYPES = Object.values(ORGANIZATION_TYPES);

export const ORGANIZATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
};

export const ALL_ORGANIZATION_STATUSES = Object.values(ORGANIZATION_STATUS);

/**
 * Strict state-machine transitions:
 * PENDING    -> APPROVED | REJECTED
 * APPROVED   -> SUSPENDED
 * SUSPENDED  -> APPROVED (via activate or approve)
 * REJECTED   -> none (terminal)
 */
export const VALID_STATUS_TRANSITIONS = {
  [ORGANIZATION_STATUS.PENDING]: [
    ORGANIZATION_STATUS.APPROVED,
    ORGANIZATION_STATUS.REJECTED,
  ],
  [ORGANIZATION_STATUS.APPROVED]: [
    ORGANIZATION_STATUS.SUSPENDED,
  ],
  [ORGANIZATION_STATUS.SUSPENDED]: [
    ORGANIZATION_STATUS.APPROVED,
  ],
  [ORGANIZATION_STATUS.REJECTED]: [],
};

export default {
  ORGANIZATION_TYPES,
  ALL_ORGANIZATION_TYPES,
  ORGANIZATION_STATUS,
  ALL_ORGANIZATION_STATUSES,
  VALID_STATUS_TRANSITIONS,
};
