export const PERMISSIONS = Object.freeze({
  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  
  // Organization Management
  MANAGE_ORGANIZATIONS: 'MANAGE_ORGANIZATIONS',
  VIEW_ORGANIZATIONS: 'VIEW_ORGANIZATIONS',

  // RBAC Management
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_ROLES: 'VIEW_ROLES',
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',

  // Security & Auditing
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // Trip Operations
  CREATE_TRIP: 'CREATE_TRIP',
  UPDATE_TRIP: 'UPDATE_TRIP',
  DELETE_TRIP: 'DELETE_TRIP',
  VIEW_TRIPS: 'VIEW_TRIPS',

  // Bus Operations
  MANAGE_BUS: 'MANAGE_BUS',
  VIEW_BUSES: 'VIEW_BUSES',

  // Route Operations
  MANAGE_ROUTES: 'MANAGE_ROUTES',
  VIEW_ROUTES: 'VIEW_ROUTES',

  // Booking & Ticketing
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
  BOOK_TICKET: 'BOOK_TICKET',
  CANCEL_TICKET: 'CANCEL_TICKET',
  VIEW_TICKETS: 'VIEW_TICKETS',
  VERIFY_TICKET: 'VERIFY_TICKET',

  // Payments & Reports
  VIEW_PAYMENTS: 'VIEW_PAYMENTS',
  VIEW_REPORTS: 'VIEW_REPORTS',
});

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS_MAPPING = Object.freeze({
  ADMIN: ALL_PERMISSIONS,
  BOOKING_COORDINATOR: [
    PERMISSIONS.VIEW_ORGANIZATIONS,
    PERMISSIONS.CREATE_TRIP,
    PERMISSIONS.UPDATE_TRIP,
    PERMISSIONS.DELETE_TRIP,
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.MANAGE_BUS,
    PERMISSIONS.VIEW_BUSES,
    PERMISSIONS.MANAGE_ROUTES,
    PERMISSIONS.VIEW_ROUTES,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.VERIFY_TICKET,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  TICKET_VERIFIER: [
    PERMISSIONS.VIEW_ORGANIZATIONS,
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.VERIFY_TICKET,
  ],
  PASSENGER: [
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.BOOK_TICKET,
    PERMISSIONS.CANCEL_TICKET,
    PERMISSIONS.VIEW_TICKETS,
  ],
});

export default PERMISSIONS;
