export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  BOOKING_COORDINATOR: 'BOOKING_COORDINATOR',
  OPERATIONAL_MANAGER: 'OPERATIONAL_MANAGER',
  PASSENGER: 'PASSENGER',
  TICKET_VERIFIER: 'TICKET_VERIFIER',
  DRIVER: 'DRIVER',
});

export const ALL_ROLES = Object.values(ROLES);

export default ROLES;
